version: 2.1
orbs:
  node: circleci/node@5.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    executor:
      name: node/default
      tag: "lts"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run YARN tests
          command: sudo yarn test
workflows:
  test_my_app:
    jobs:
      - test
