version: 2.1
orbs:
  node: circleci/node@5.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
      tag: << parameters.node-version >>
    steps:
      - checkout
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run YARN tests
          command: sudo yarn test
workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["10", "11", "12", "13"]
