version: 2.1
orbs:
  node: circleci/node@5.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    executor:
      name: node/default
      tag: "lts"
    steps:
      - checkout
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run YARN tests
          command: sudo yarn test
workflows:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 13.11.0
                - 12.16.0
                - 10.19.0
  test_my_app:
    jobs:
      - test
